_posts/2016-11-01-about-chainer-blog.md

Minor edits to improve wording.

Edited about-chainer-blog page for wording

---

index.html

Added slides

---

_includes/head.html
_includes/header.html
css/style.css

I replaced share buttons with font-awesome buttons.

Fix header

---

_includes/head.html

The current page shows corrupted HTML on load. I fixed CSS and javascript to hide the corrupted page.

Use fadein to hide corrupted HTML

---

_layouts/archive.html
_layouts/category.html
_layouts/post.html
blog/index.html

Fix url in share buttons

---

_layouts/post.html

Fix arrow style

---

css/style.css
index.html

Some external URLs should be https://~

Fix http to https

---

_config.yml

Update to v2.0.1

---

index.html

Fix repository URL

---

index.html

Fixes inconsistent indentation of `index.html`.

Fix indentation

---

_config.yml

Update to v3.1.0

---

_includes/head.html
js/init.js

See also: https://toddmotto.com/cache-busting-jekyll-github-pages

Add timestamp to script and CSS to avoid caching

---

_posts/2018-01-17-onnx-support-by-chainer.md

Reverts chainer/chainer.org#59

Revert "Revert "ONNX support by Chainer""

---

index.html

Remove old slides from the top page

---

_layouts/category.html

Currently it lists all articles.
https://chainer.org/blog/category/announcement/

Fix per-category view not working as expected

---

_includes/header.html

"Documents" sounds strange for me.

Documents -> Documentation

---

_posts/2019-05-16-released-v6.md

I would like to make this post merged right after the release of chainer/cupy v6.

v6 blog post

---

_config.yml

Update to v6.2.0

---

_config.yml

Bump version to v6.4.0

---

_config.yml

Bump to v6.5.0

---

_config.yml

Bump to v7.0.0

---

_config.yml

Bump to v7.1.0

---

_config.yml

Bump to v7.2.0

---

css/style.css
index.html

Add maintenance announcement
